  export default {
    success: "success",
    selects: document.querySelectorAll(".select"),
    amountInput: document.getElementById('amount'),
    form: document.querySelector(".form"),
    resultFrom: document.getElementById("resultFrom"),
    resultTo: document.getElementById("resultTo"),
    formResults: document.querySelector(".form_results"),
    rateConversion: document.querySelector(".rate_conversion"),
    rateLast: document.querySelector(".rate_last"),
    switchButton: document.querySelector(".switch_currencies"),
    toSelect: document.getElementById("to"),
    fromSelect: document.getElementById("from"),
    tabs: document.querySelectorAll('.tab'),
    currentCurrency: document.querySelector(".currency_single_item"),
    currentCurrencyList: document.querySelector(".currency_list"),
    singleSelect: document.getElementById("singleSelect"),
    addButton: document.querySelector(".currency_add_button"),
    addCurrencySelect: document.getElementById("addCurrencySelect"),
};